"""
Fixed seed data for the sales analytics portfolio project.

This file contains the business backbone that should not be randomized:
customers, regions, vehicle models, products, customer-product coverage,
and the strict product-to-vehicle mappings provided in the project brief.
"""

from __future__ import annotations

SEED = 42
START_DATE = "2024-01-01"
END_DATE = "2025-12-31"

EVENT_ORDER = [
    "recurring_promotion",
    "one_off_bulk_order",
    "recall_warranty",
    "new_dealer_launch",
    "extreme_promotion",
    "promotion_absence",
    "hidden_drop",
    "new_normal_shift",
    "mixed_ambiguous_behavior",
]

REGIONS = [
    {
        "region_id": "REGION_SE",
        "region_name": "Stockholm Metro",
        "market_type": "urban_core",
    },
    {
        "region_id": "REGION_SE_W",
        "region_name": "West Sweden",
        "market_type": "mixed_urban",
    },
    {
        "region_id": "REGION_SE_E",
        "region_name": "East Central Sweden",
        "market_type": "growth_corridor",
    },
    {
        "region_id": "REGION_SE_N",
        "region_name": "North Sweden",
        "market_type": "sparse_regional",
    },
]

CUSTOMERS = [
    {
        "customer_id": "CUST_A",
        "customer_name": "NordAuto Stockholm",
        "customer_contact_name": "Anna Lindberg",
        "delivery_address": "Sveavagen 18, 111 57 Stockholm",
        "region_id": "REGION_SE",
        "order_cycle": "weekly",
        "channel_type": "dealer",
        "dealer_launch_date": "2020-01-06",
        "customer_status": "active",
        "customer_size": "large",
        "size_multiplier": 1.85,
        "baseline_volatility": 0.05,
        "role_description": "large established dealer",
    },
    {
        "customer_id": "CUST_B",
        "customer_name": "Svea Mobility Parts",
        "customer_contact_name": "Erik Sjostrom",
        "delivery_address": "Lindholmsallén 14, 417 55 Gothenburg",
        "region_id": "REGION_SE_W",
        "order_cycle": "biweekly",
        "channel_type": "dealer",
        "dealer_launch_date": "2021-03-15",
        "customer_status": "active",
        "customer_size": "mid",
        "size_multiplier": 1.05,
        "baseline_volatility": 0.06,
        "role_description": "mid-size stable dealer",
    },
    {
        "customer_id": "CUST_C",
        "customer_name": "PromoDrive Retail",
        "customer_contact_name": "Maja Holm",
        "delivery_address": "Magasinsgatan 7, 411 18 Gothenburg",
        "region_id": "REGION_SE_W",
        "order_cycle": "weekly",
        "channel_type": "retail_partner",
        "dealer_launch_date": "2022-09-05",
        "customer_status": "active",
        "customer_size": "mid",
        "size_multiplier": 0.95,
        "baseline_volatility": 0.08,
        "role_description": "promo-sensitive dealer",
    },
    {
        "customer_id": "CUST_D",
        "customer_name": "NewMotion Uppsala",
        "customer_contact_name": "Johan Ek",
        "delivery_address": "Stationsgatan 24, 753 40 Uppsala",
        "region_id": "REGION_SE_E",
        "order_cycle": "weekly",
        "channel_type": "dealer",
        "dealer_launch_date": "2024-03-04",
        "customer_status": "active",
        "customer_size": "small",
        "size_multiplier": 0.70,
        "baseline_volatility": 0.07,
        "role_description": "newly launched dealer",
    },
    {
        "customer_id": "CUST_E",
        "customer_name": "Arctic Niche Auto",
        "customer_contact_name": "Sara Nyberg",
        "delivery_address": "Storgatan 9, 972 38 Lulea",
        "region_id": "REGION_SE_N",
        "order_cycle": "monthly",
        "channel_type": "independent_shop",
        "dealer_launch_date": "2021-06-07",
        "customer_status": "active",
        "customer_size": "small",
        "size_multiplier": 0.50,
        "baseline_volatility": 0.14,
        "role_description": "small volatile dealer",
    },
]

VEHICLE_MODELS = [
    {"vehicle_model_id": "VM001", "vehicle_model_name": "Aurora Sedan", "platform_type": "ICE"},
    {"vehicle_model_id": "VM002", "vehicle_model_name": "Fjord SUV", "platform_type": "ICE"},
    {"vehicle_model_id": "VM003", "vehicle_model_name": "Polaris Wagon", "platform_type": "Hybrid"},
    {"vehicle_model_id": "VM004", "vehicle_model_name": "Voltis Compact", "platform_type": "EV"},
    {"vehicle_model_id": "VM005", "vehicle_model_name": "Eon Crossover", "platform_type": "EV"},
]

PRODUCTS = [
    {
        "product_id": "P1",
        "product_name": "Core Oil Filter",
        "category_l1": "Maintenance",
        "category_l2": "Filters",
        "substitute_type": "direct",
        "platform_type": "ICE",
        "effort_type": "effort_less",
        "effort_rule_id": "RULE_01",
        "lifecycle_stage": "mature",
        "scenario_role": "stable_baseline",
        "base_daily_demand": 1.05,
        "list_price": 180.0,
    },
    {
        "product_id": "P2",
        "product_name": "Universal Cabin Filter",
        "category_l1": "Maintenance",
        "category_l2": "Filters",
        "substitute_type": "direct",
        "platform_type": "All",
        "effort_type": "effort_less",
        "effort_rule_id": "RULE_01",
        "lifecycle_stage": "mature",
        "scenario_role": "stable_baseline",
        "base_daily_demand": 0.90,
        "list_price": 165.0,
    },
    {
        "product_id": "P3",
        "product_name": "Campaign Brake Pad Kit",
        "category_l1": "Service",
        "category_l2": "Brakes",
        "substitute_type": "limited",
        "platform_type": "All",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "mature",
        "scenario_role": "recurring_promo",
        "base_daily_demand": 0.75,
        "list_price": 420.0,
    },
    {
        "product_id": "P4",
        "product_name": "Seasonal Wiper Set",
        "category_l1": "Service",
        "category_l2": "Visibility",
        "substitute_type": "direct",
        "platform_type": "All",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "mature",
        "scenario_role": "recurring_promo",
        "base_daily_demand": 0.60,
        "list_price": 210.0,
    },
    {
        "product_id": "P5",
        "product_name": "Workshop Battery Pack",
        "category_l1": "Repair",
        "category_l2": "Electrical",
        "substitute_type": "project_specific",
        "platform_type": "ICE",
        "effort_type": "mixed",
        "effort_rule_id": "RULE_03",
        "lifecycle_stage": "mature",
        "scenario_role": "one_off_bulk",
        "base_daily_demand": 0.42,
        "list_price": 980.0,
    },
    {
        "product_id": "P6",
        "product_name": "Cooling Recall Repair Kit",
        "category_l1": "Repair",
        "category_l2": "Cooling",
        "substitute_type": "none",
        "platform_type": "ICE",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "mature",
        "scenario_role": "recall_warranty",
        "base_daily_demand": 0.25,
        "list_price": 760.0,
    },
    {
        "product_id": "P7",
        "product_name": "Launch Essentials Bundle",
        "category_l1": "Dealer Launch",
        "category_l2": "Starter Pack",
        "substitute_type": "bundle",
        "platform_type": "All",
        "effort_type": "mixed",
        "effort_rule_id": "RULE_03",
        "lifecycle_stage": "growth",
        "scenario_role": "new_dealer",
        "base_daily_demand": 0.35,
        "list_price": 640.0,
    },
    {
        "product_id": "P8",
        "product_name": "Alignment Sensor Kit",
        "category_l1": "Repair",
        "category_l2": "Sensors",
        "substitute_type": "limited",
        "platform_type": "All",
        "effort_type": "mixed",
        "effort_rule_id": "RULE_03",
        "lifecycle_stage": "mature",
        "scenario_role": "hidden_drop",
        "base_daily_demand": 0.58,
        "list_price": 530.0,
    },
    {
        "product_id": "P9",
        "product_name": "Promo Support Air Filter",
        "category_l1": "Maintenance",
        "category_l2": "Filters",
        "substitute_type": "direct",
        "platform_type": "All",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "mature",
        "scenario_role": "promo_absence",
        "base_daily_demand": 0.68,
        "list_price": 195.0,
    },
    {
        "product_id": "P10",
        "product_name": "Flash Sale Charge Cable",
        "category_l1": "Accessories",
        "category_l2": "Charging",
        "substitute_type": "direct",
        "platform_type": "All",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "growth",
        "scenario_role": "extreme_promo",
        "base_daily_demand": 0.36,
        "list_price": 350.0,
    },
    {
        "product_id": "P11",
        "product_name": "ICE Ignition Coil",
        "category_l1": "Powertrain",
        "category_l2": "Ignition",
        "substitute_type": "direct",
        "platform_type": "ICE",
        "effort_type": "effort_less",
        "effort_rule_id": "RULE_01",
        "lifecycle_stage": "late_mature",
        "scenario_role": "new_normal_ice_decline",
        "base_daily_demand": 0.62,
        "list_price": 410.0,
    },
    {
        "product_id": "P12",
        "product_name": "ICE Fuel System Cleaner",
        "category_l1": "Powertrain",
        "category_l2": "Fuel",
        "substitute_type": "direct",
        "platform_type": "ICE",
        "effort_type": "effort_less",
        "effort_rule_id": "RULE_01",
        "lifecycle_stage": "late_mature",
        "scenario_role": "new_normal_ice_decline",
        "base_daily_demand": 0.70,
        "list_price": 260.0,
    },
    {
        "product_id": "P13",
        "product_name": "EV Thermal Module",
        "category_l1": "EV Service",
        "category_l2": "Thermal",
        "substitute_type": "limited",
        "platform_type": "EV",
        "effort_type": "effort_driven",
        "effort_rule_id": "RULE_02",
        "lifecycle_stage": "growth",
        "scenario_role": "new_normal_ev_growth",
        "base_daily_demand": 0.38,
        "list_price": 890.0,
    },
    {
        "product_id": "P14",
        "product_name": "Hybrid Demand Diagnostic Pack",
        "category_l1": "Diagnostics",
        "category_l2": "Mixed Pattern",
        "substitute_type": "bundle",
        "platform_type": "All",
        "effort_type": "mixed",
        "effort_rule_id": "RULE_03",
        "lifecycle_stage": "mature",
        "scenario_role": "mixed_ambiguous",
        "base_daily_demand": 0.48,
        "list_price": 610.0,
    },
]

PRODUCT_VEHICLE_MAP = {
    "P1": ["VM001", "VM002", "VM003"],
    "P2": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P3": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P4": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P5": ["VM001", "VM002"],
    "P6": ["VM001", "VM002"],
    "P7": ["VM001", "VM002", "VM003"],
    "P8": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P9": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P10": ["VM001", "VM002", "VM003", "VM004", "VM005"],
    "P11": ["VM001", "VM002"],
    "P12": ["VM001", "VM002"],
    "P13": ["VM004", "VM005"],
    "P14": ["VM001", "VM002", "VM003", "VM004", "VM005"],
}

CUSTOMER_PRODUCT_RELATIONSHIPS = {
    "CUST_A": {
        "P1": 1.00,
        "P2": 1.00,
        "P3": 0.95,
        "P4": 0.90,
        "P5": 0.80,
        "P6": 0.85,
        "P7": 0.40,
        "P8": 0.95,
        "P9": 0.75,
        "P10": 0.55,
        "P11": 0.85,
        "P12": 0.88,
        "P13": 0.50,
        "P14": 0.72,
    },
    "CUST_B": {
        "P1": 0.82,
        "P2": 0.86,
        "P3": 0.70,
        "P4": 0.62,
        "P5": 0.55,
        "P6": 0.65,
        "P8": 0.72,
        "P9": 0.58,
        "P11": 0.70,
        "P12": 0.74,
        "P13": 0.35,
        "P14": 0.42,
    },
    "CUST_C": {
        "P2": 0.65,
        "P3": 1.00,
        "P4": 0.95,
        "P9": 0.92,
        "P10": 0.90,
        "P14": 0.60,
    },
    "CUST_D": {
        "P2": 0.42,
        "P3": 0.35,
        "P7": 1.00,
        "P13": 0.48,
        "P14": 0.30,
    },
    "CUST_E": {
        "P1": 0.30,
        "P4": 0.46,
        "P8": 0.38,
        "P10": 0.28,
        "P14": 0.34,
    },
}

EFFORT_RULES = [
    {
        "effort_rule_id": "RULE_01",
        "effort_classification": "baseline_repeat",
        "rule_description": "Mostly steady demand with low commercial intervention.",
    },
    {
        "effort_rule_id": "RULE_02",
        "effort_classification": "campaign_driven",
        "rule_description": "Demand reacts strongly when discounts or campaigns are applied.",
    },
    {
        "effort_rule_id": "RULE_03",
        "effort_classification": "mixed_signal",
        "rule_description": "Demand reflects both normal replenishment and scenario-specific disruption.",
    },
]
